### ISSUE TITLE
On text-editing with Japanese IM

### ISSUE THREAD

**Issue by ymatz** [inkdropapp/forum#22] opened 2016-12-02 07:23 UTC
When I edit notes in Inkdrop using Japanese input methods and do kana-to-kanji conversions, the underlines showing unspecified strings (未確定文字列) are somehow not being separated at the borders of 文節, which is annoying. I tried the macOS Sierra standard input method and ATOK, and found the both behave the same regarding this point. I hope this behavior to be fixed.

**Comment by craftzdog** [comment] 2016-12-02 08:06
Hi, thanks for your suggestion.
I see the problem impossible to know which characters will be converted and committed since the editor just adding underline to the group of current composition.
Inkdrop internally uses CodeMirror for its editor and it's caused by how it's implemented.
This problem is discussed [here](https://github.com/codemirror/CodeMirror/issues/4095) but it seems to be difficult to solve because the browser doesn't provide enough information.

There is one way to avoid it, which is switching to `inputStyle: 'contenteditable'` but it causes some other interface problems and seems to be not performant.
For the moment it unfortunately can't be solved and it needs more research.

**Comment by ymatz** [comment] 2016-12-02 09:18
Okay, I see, so it's a problem of CodeMirror. It's not a very good news, but thanks anyway for your response.

**Comment by craftzdog** [comment] 2016-12-02 09:38
Sorry for that. I'm also Japanese and I'd prefer to support it though.

**Closed as completed** 2016-12-21 11:55 UTC
Labels: wontfix
