### ISSUE TITLE
Editor ignores changes made by other device

### ISSUE THREAD

**Issue by beeblebrox3** [inkdropapp/forum#51] opened 2017-07-01 20:17 UTC
## Bug report
Edit a note while it is open on another instance (on another computer, tablet, phone etc) can lead to data loss.

### Info
- Platform: Linux, Android, iOS;
- Platform version: ElementaryOS 0.4.1;
- App Version: (3.6.0);

### Reproduce
- Create a new note and put an "A" on the Computer A;
- Save the note;
- The App will show the "Syncing..." message;
- Open the same note on the Computer B;
- The note will have "A". Now edit this note and add an "B";
- The App will show the "Syncing..." message on the Computer B and then on Computer A;
- On the sidebar in both instances the preview will show "AB", but the editor on Computer A will show only the "A" (old content). If the you give focus to the editor and then click on the note on the sidebar it will sync the content (only the "A") and update the note on the server. The preview on Computer B will show just the "A", but the editor still shows "AB".

**Question:** how difficult is implement something like the editor of google docs or dropbox paper, where you can edit the same document on different devices without conflict?

**Comment by craftzdog** [comment] 2017-07-02 01:31
Hi Luís,

Thank you for the report!
I managed to reproduce the problem that an opened note won't be synced correctly to the latest state changed from other device.
The editor component unexpectedly ignored the changes.
It will be fixed in the next version soon!

**Answer**:
Inkdrop relies on CouchDB's HTTP long-poll based synchronization.
Google Docs and Dropbox Paper offer real-time sync including cursor position whereas CouchDB is a document based database.
It is necessary to implement additional sync mechanism specifically for the real-time sync.
Inkdrop is made for personal use and is not a service for collaboration and teamwork like Google Docs, so it's unfortunately not planned to be supported.

**Comment by beeblebrox3** [comment] 2017-07-03 11:22
Thanks!

My question was not because I want to collaborate with other people, but for handling de conflicts between versions of the same document. Sometimes I just start to write a note on my computer and go to another place to continue on my phone or iPad. Depending of the time it takes to sync I end up losing data. Simplenote was the fastest that I've used, but the simplicity of the editor wasn't enought for me.
But that's ok. Inkdrop show to me when it is syncing and on mobile apps we have a button to force the sync. Is enought, I think.

Thanks for the great app! :+1:

**Comment by craftzdog** [comment] 2017-07-04 06:18
Resolved in v3.6.1.
Thanks again for your report :D

You are right. It always takes several seconds to sync so you have to wait until it finished so that you can edit same note, or you will lost the data.
Merging diffs for automatically resolving conflicts is not supported at this point because it's very rarely happened in my experience.
Please check if the editor correctly shows the latest data on v3.6.1. 😃

**Closed as completed by craftzdog** 2017-07-04 06:18 UTC
Labels: bug

**Comment by beeblebrox3** [comment] 2017-07-04 11:48
It's working fine now. Thanks.
You won't provide `.deb` files anymore?

**Comment by craftzdog** [comment] 2017-07-04 11:53
Oops, the link was missing. deb file is [here](https://github.com/inkdropapp/releases/releases/download/v3.6.1/inkdrop_3.6.1_amd64.deb)!
Thanks!
